version: "1.0"
services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  #    environment:
  #      - STORAGE_TYPE=elasticsearch
  #      - ES_HOSTS=http://elasticsearch:9200
  #    depends_on:
  #      - elasticsearch

  #  elasticsearch:
  #    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
  #    container_name: elasticsearch
  #    environment:
  #      - discovery.type=single-node
  #      - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #    ports:
  #      - "9200:9200"
  #    volumes:
  #      - "$PWD/esdata/:/usr/share/elasticsearch/data"
  #
  #  kibana:
  #    image: docker.elastic.co/kibana/kibana:7.10.2
  #    container_name: kibana
  #    ports:
  #      - "5601:5601"
  #    environment:
  #      ELASTICSEARCH_URL: http://elasticsearch:9200
  #    depends_on:
  #      - elasticsearch

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.10.2
  #   container_name: logstash
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   ports:
  #     - "5044:5044"
  #   depends_on:
  #     - elasticsearch

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.10.2
  #   container_name: filebeat
  #   volumes:
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - "$PWD/log:/app/log"
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   depends_on:
  #     - elasticsearch

volumes:
  esdata:
    driver: local

  # mysql :
  #   image : alicek106/composetest:mysql
  #   command: mysqld
