server:
  port: 8083

spring:
  application:
    name: sse-service
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      sns:
        topic:
          arn: ${AWS_TOPIC_ARC}
      sqs:
        queue:
          name: ${AWS_QUEUE_NAME}
