server:
  port: 8083

spring:
  application:
    name: sse-service
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      sns:
        topic:
          arn: ${AWS_TOPIC_ARC}
      sqs:
        queue:
          name: ${AWS_QUEUE_NAME}

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3_multi
  zipkin:
    tracing:
      kafka:
        topic: "zipkin-test"
      endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  brokers: localhost:19094
  topic: zipkin-topic
  group-id: zipkin-group
