server:
  port: 8089

spring:
  application:
    name: student-service

  #  r2dbc:
  #    url: r2dbc:mysql://localhost:3306/yb
  #    username: yb
  #    password: 1234
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/yb
        username: yb
        password: 1234
        maximum-pool-size: 50
        driver-class-name: com.mysql.cj.jdbc.Driver
      properties:
        hibernate:
          hbm2ddl.auto: update
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"


#management:
#  endpoints:
#  tracing:
#    sampling:
#      probability: 1.0
#    propagation:
#      consume: b3
#      produce: b3_multi
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"

#  application:
#    name: student-service  # 서비스 이름 설정
#  sleuth:
#    sampler:
#      probability: 1.0  # 샘플링 비율 (0.0 ~ 1.0)
#  zipkin:
#    base-url: http://localhost:9411  # Zipkin 서버 주소