#spring:
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}


kafka:
  brokers: localhost:19094
  topic: zipkin-topic
  group-id: zipkin-group
#  max-poll-records: 3
#  enable-auto-commit: false
#  auto-offset-reset: latest

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: health,info,metrics

#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
